spring:
    datasource:
        url: jdbc:mysql://localhost:3306/batch_demo
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver

    batch:
        jdbc:
            initialize-schema: always
        job:
            enabled: false

    mail:
        host: smtp.example.com
        port: 587
        username: your-email@example.com
        password: your-password
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.batch.domain